# This is a basic workflow to help you get started with Actions

name: Prod 

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [^16.10.0]

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Yarn
      run: npm install -g yarn
    - name: Install firebase
      run: npm install -g firebase-tools firebase
    - name: Install Dependencies
      run: yarn install
    - name: Build Production
      run: yarn build
      env:
        CI: false
    - name: Deploy to firebase
      run: |
        firebase use default --token ${{ secrets.FIREBASE_TOKEN }}
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only hosting:prod